### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.`

### ISSUE THREAD

**Issue by Murphy-OrangeMud** [ptillet/torch-blocksparse#21]
Hi, 
I encountered a build fail during my build from the source code. I have tried to build from the stable version using pip but it failed either.

`running install
running bdist_egg
running egg_info
writing torch_blocksparse.egg-info/PKG-INFO
writing dependency_links to torch_blocksparse.egg-info/dependency_links.txt
writing requirements to torch_blocksparse.egg-info/requires.txt
writing top-level names to torch_blocksparse.egg-info/top_level.txt
/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/utils/cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'torch_blocksparse.egg-info/SOURCES.txt'
writing manifest file 'torch_blocksparse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.6/torch_blocksparse_cpp_utils.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/batchnorm.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/matmul.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/attention.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/permute.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/deepspeedsparseselfattention.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/__init__.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/conv.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/relu.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
copying build/lib.linux-x86_64-3.6/torch_blocksparse/softmax.py -> build/bdist.linux-x86_64/egg/torch_blocksparse
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/batchnorm.py to batchnorm.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/matmul.py to matmul.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/attention.py to attention.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/permute.py to permute.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/deepspeedsparseselfattention.py to deepspeedsparseselfattention.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/conv.py to conv.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/relu.py to relu.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse/softmax.py to softmax.cpython-36.pyc
creating stub loader for torch_blocksparse_cpp_utils.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torch_blocksparse_cpp_utils.py to torch_blocksparse_cpp_utils.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_blocksparse.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_blocksparse.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_blocksparse.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_blocksparse.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_blocksparse.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.torch_blocksparse_cpp_utils.cpython-36: module references __file__
creating 'dist/torch_blocksparse-1.1.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_blocksparse-1.1.0-py3.6-linux-x86_64.egg
removing '/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/torch_blocksparse-1.1.0-py3.6-linux-x86_64.egg' (and everything under it)
creating /home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/torch_blocksparse-1.1.0-py3.6-linux-x86_64.egg
Extracting torch_blocksparse-1.1.0-py3.6-linux-x86_64.egg to /home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages
torch-blocksparse 1.1.0 is already the active version in easy-install.pth

Installed /home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/torch_blocksparse-1.1.0-py3.6-linux-x86_64.egg
Processing dependencies for torch-blocksparse==1.1.0
Searching for triton
Reading https://pypi.org/simple/triton/
Downloading https://files.pythonhosted.org/packages/27/d2/adc02ff11f58199fc3b0f75623a9e8244060339432adf40332c22b59a483/triton-0.2.1.tar.gz#sha256=d512855964f4d1e004370efbe9e1d2bb215fdd1b1f91a02d5e8ae1965c671b2e
Best match: triton 0.2.1
Processing triton-0.2.1.tar.gz
Writing /tmp/easy_install-sj3hife9/triton-0.2.1/setup.cfg
Running triton-0.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sj3hife9/triton-0.2.1/egg-dist-tmp-54zmd0kt
/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'keyword'
  warnings.warn(msg)
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM: /usr/lib/llvm-8 (found version "8.0.0")
-- Adding Python module
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/easy_install-sj3hife9/triton-0.2.1/build/temp.linux-x86_64-3.6
Scanning dependencies of target triton
[  1%] Building CXX object CMakeFiles/triton.dir/lib/runtime/arg.cc.o
[  3%] Building CXX object CMakeFiles/triton.dir/lib/lang/encoding.cc.o
[  7%] Building CXX object CMakeFiles/triton.dir/lib/lang/type.cc.o
[  7%] Building CXX object CMakeFiles/triton.dir/lib/runtime/function.cc.o
[  9%] Building CXX object CMakeFiles/triton.dir/lib/lang/error.cc.o
[ 10%] Building CXX object CMakeFiles/triton.dir/lib/lang/code_gen.cc.o
[ 12%] Building CXX object CMakeFiles/triton.dir/lib/lang/scope.cc.o
[ 14%] Building CXX object CMakeFiles/triton.dir/lib/lang/evaluator.cc.o
[ 16%] Building CXX object CMakeFiles/triton.dir/lib/lang/scanner.cc.o
[ 18%] Building CXX object CMakeFiles/triton.dir/lib/lang/token.cc.o
[ 20%] Building CXX object CMakeFiles/triton.dir/lib/lang/cpp.cc.o
[ 21%] Building CXX object CMakeFiles/triton.dir/lib/lang/parser.cc.o
[ 23%] Building CXX object CMakeFiles/triton.dir/lib/lang/ast.cc.o
[ 25%] Building CXX object CMakeFiles/triton.dir/lib/ir/type.cc.o
[ 27%] Building CXX object CMakeFiles/triton.dir/lib/ir/constant.cc.o
[ 29%] Building CXX object CMakeFiles/triton.dir/lib/ir/instructions.cc.o
[ 30%] Building CXX object CMakeFiles/triton.dir/lib/ir/context.cc.o
[ 32%] Building CXX object CMakeFiles/triton.dir/lib/ir/builder.cc.o
[ 34%] Building CXX object CMakeFiles/triton.dir/lib/ir/value.cc.o
[ 36%] Building CXX object CMakeFiles/triton.dir/lib/ir/module.cc.o
[ 38%] Building CXX object CMakeFiles/triton.dir/lib/ir/metadata.cc.o
[ 40%] Building CXX object CMakeFiles/triton.dir/lib/ir/function.cc.o
[ 41%] Building CXX object CMakeFiles/triton.dir/lib/ir/basic_block.cc.o
[ 43%] Building CXX object CMakeFiles/triton.dir/lib/ir/print.cc.o
[ 45%] Building CXX object CMakeFiles/triton.dir/lib/ir/utils.cc.o
[ 47%] Building CXX object CMakeFiles/triton.dir/lib/driver/platform.cc.o
[ 49%] Building CXX object CMakeFiles/triton.dir/lib/driver/context.cc.o
[ 50%] Building CXX object CMakeFiles/triton.dir/lib/driver/buffer.cc.o
[ 52%] Building CXX object CMakeFiles/triton.dir/lib/driver/dispatch.cc.o
[ 54%] Building CXX object CMakeFiles/triton.dir/lib/driver/error.cc.o
[ 56%] Building CXX object CMakeFiles/triton.dir/lib/driver/module.cc.o
[ 58%] Building CXX object CMakeFiles/triton.dir/lib/driver/stream.cc.o
[ 60%] Building CXX object CMakeFiles/triton.dir/lib/driver/event.cc.o
[ 61%] Building CXX object CMakeFiles/triton.dir/lib/driver/backend.cc.o
[ 63%] Building CXX object CMakeFiles/triton.dir/lib/driver/handle.cc.o
[ 65%] Building CXX object CMakeFiles/triton.dir/lib/driver/device.cc.o
[ 67%] Building CXX object CMakeFiles/triton.dir/lib/driver/kernel.cc.o
[ 69%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/coalesce.cc.o
[ 70%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/disassociate.cc.o
[ 72%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/membar.cc.o
[ 74%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/cts.cc.o
[ 76%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/reassociate.cc.o
[ 78%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/dce.cc.o
[ 80%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/peephole.cc.o
[ 81%] Building CXX object CMakeFiles/triton.dir/lib/codegen/selection/generator.cc.o
[ 83%] Building CXX object CMakeFiles/triton.dir/lib/codegen/selection/machine_value.cc.o
[ 85%] Building CXX object CMakeFiles/triton.dir/lib/codegen/selection/machine_layout.cc.o
[ 87%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/liveness.cc.o
/tmp/easy_install-sj3hife9/triton-0.2.1/src/lib/codegen/selection/generator.cc: In member function ‘virtual void triton::codegen::generator::visit_atomic_add_inst(triton::ir::atomic_add_inst*)’:
/tmp/easy_install-sj3hife9/triton-0.2.1/src/lib/codegen/selection/generator.cc:662:62: error: no matching function for call to ‘llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::CreateAtomicRMW(llvm::Instruction::BinaryOps, triton::codegen::Value*&, triton::codegen::Value*&, llvm::AtomicOrdering, llvm::SyncScope::<unnamed enum>)’
                                             SyncScope::System);
                                                              ^
In file included from /tmp/easy_install-sj3hife9/triton-0.2.1/src/lib/codegen/selection/generator.cc:15:0:
/usr/lib/llvm-8/include/llvm/IR/IRBuilder.h:1452:18: note: candidate: llvm::AtomicRMWInst* llvm::IRBuilder<T, Inserter>::CreateAtomicRMW(llvm::AtomicRMWInst::BinOp, llvm::Value*, llvm::Value*, llvm::AtomicOrdering, llvm::SyncScope::ID) [with T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter; llvm::SyncScope::ID = unsigned char]
   AtomicRMWInst *CreateAtomicRMW(AtomicRMWInst::BinOp Op, Value *Ptr, Value *Val,
                  ^~~~~~~~~~~~~~~
/usr/lib/llvm-8/include/llvm/IR/IRBuilder.h:1452:18: note:   no known conversion for argument 1 from ‘llvm::Instruction::BinaryOps’ to ‘llvm::AtomicRMWInst::BinOp’
[ 89%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/align.cc.o
CMakeFiles/triton.dir/build.make:1118: recipe for target 'CMakeFiles/triton.dir/lib/codegen/selection/generator.cc.o' failed
make[2]: *** [CMakeFiles/triton.dir/lib/codegen/selection/generator.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/triton.dir/all' failed
make[1]: *** [CMakeFiles/triton.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-sj3hife9/triton-0.2.1/setup.py", line 123, in <module>
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-sj3hife9/triton-0.2.1/setup.py", line 53, in run
  File "/tmp/easy_install-sj3hife9/triton-0.2.1/setup.py", line 89, in build_extension
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    cmdclass         = cmdclass
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 714, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 759, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    replace_conflicting=replace_conflicting
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 712, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 897, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1167, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1151, in run_setup
    run_setup(setup_script, args)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-sj3hife9/triton-0.2.1/setup.py", line 123, in <module>
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-sj3hife9/triton-0.2.1/setup.py", line 53, in run
  File "/tmp/easy_install-sj3hife9/triton-0.2.1/setup.py", line 89, in build_extension
  File "/home/chengzhiyi/anaconda3/envs/pcgcn/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.`

My environment is: 
Platform: Ubuntu 16.04 LTS (GNU/Linux 2.6.32-042stab134.3 x86_64)
GCC/G++: 7.5.0
CMake: 3.5.1
Python: 3.6.10
LLVM: 8

**Comment by ptillet** [comment]
Hi! This project now requires llvm-9 rather than llvm-8. I will update the requirements accordingly.

**Comment by Murphy-OrangeMud** [comment]
Thanks. The problem is solved.
