### ISSUE TITLE
ImportError: No module named 'sdd_segment'

### ISSUE THREAD

**Issue by EDLMM** [ptillet/torch-blocksparse#23]
Hi, here is the error occurred while I'm trying to import torch_blocksparse
```
>>> import torch
>>> import torch_blocksparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home3/liyz/venv_tbs_2/lib/python3.6/site-packages/torch_blocksparse/__init__.py", line 2, in <module>
    from .matmul import MatMul, Linear
  File "/home3/liyz/venv_tbs_2/lib/python3.6/site-packages/torch_blocksparse/matmul.py", line 209, in <module>
    class _sparse_matmul(torch.autograd.Function):
  File "/home3/liyz/venv_tbs_2/lib/python3.6/site-packages/torch_blocksparse/matmul.py", line 400, in _sparse_matmul
    extra_cflags=['-O2', '-fopenmp']).sdd_segment
  File "/home3/liyz/venv_tbs_2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1124, in load_inline
    keep_intermediates=keep_intermediates)
  File "/home3/liyz/venv_tbs_2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1190, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home3/liyz/venv_tbs_2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1534, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home3/liyz/python36/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'sdd_segment'
>>> exit()
```

Environment info:
1. OS: Ubuntu 16.04.6 LTS.
2. python version: virtualenv based on python3.6.9
3. Since I don't have the root user access for the `sudo apt-get install` operation, I just download clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04 from (here)[https://github.com/llvm/llvm-project/releases/tag/llvmorg-9.0.1] and add the bin folder to PATH.
4. I used `pip install torch-blocksparse` rather from source.
5. Tried both gcc of version 5.5 and 7.4.
6. Tried both cuda of version 10.1 and 10.2
7. modified ['ninja','-v'] to ['ninja','--version'] in .../site-packages/torch/utils/cpp_extension.py . ( otherwise a ninja error will orcur)

I'm not sure that if I missed something necessary for the installation. Could you help me out of this? Thanks!

**Comment by ptillet** [comment]
Hey!

Thanks for pointing this out. Can you pip uninstall torch-blocksparse and pip install torch-blocksparse ? I have upgraded the version on pip.

**Comment by EDLMM** [comment]
Thanks for your reply and update.
I've solve the problem by reinstall the packages in a conda environment.
